// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhYIEEZtUHrRTndk0bxzBE94IXQ589qnI',
    appId: '1:717682395181:web:2f8787fadeed34336850a4',
    messagingSenderId: '717682395181',
    projectId: 'korepetycje12',
    authDomain: 'korepetycje12.firebaseapp.com',
    storageBucket: 'korepetycje12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4QBUNhfXOcPNSV_ewodz-fdXId8weDTE',
    appId: '1:717682395181:android:a80d58a31b912e996850a4',
    messagingSenderId: '717682395181',
    projectId: 'korepetycje12',
    storageBucket: 'korepetycje12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6xO_f_G3NY-3R96DvRMmKGzrDzhJ6y2I',
    appId: '1:717682395181:ios:6b9d8b697cb1365e6850a4',
    messagingSenderId: '717682395181',
    projectId: 'korepetycje12',
    storageBucket: 'korepetycje12.appspot.com',
    iosClientId: '717682395181-akv4771pr7ka1h31cbunsalqgsbdt6ca.apps.googleusercontent.com',
    iosBundleId: 'com.karolinasadlik.uporzadkowaneKorepetycje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6xO_f_G3NY-3R96DvRMmKGzrDzhJ6y2I',
    appId: '1:717682395181:ios:4e7126b43f0c62c06850a4',
    messagingSenderId: '717682395181',
    projectId: 'korepetycje12',
    storageBucket: 'korepetycje12.appspot.com',
    iosClientId: '717682395181-2u2r5sc76hb0n9o9akpmtcqfg48g692u.apps.googleusercontent.com',
    iosBundleId: 'com.karolinasadlik.uporzadkowaneKorepetycje.RunnerTests',
  );
}
